name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/Skinora-Backend
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d

      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "**:white_check_mark: Skinora Backend deployed successfully to server!** :rocket:"
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
